version: '3.3'

# Define the services/containers to be run
services:
  git:
    build: .

  enigma:
    build: enigma-client # specify the directory of the Dockerfile
#    volumes:
#      - ./enigma-client/dist/enigma-client:/usr/share/nginx/html
    ports:
      - "4200:80" # specify port forewarding

  enigma-server:
    build: enigma-server # specify the directory of the Dockerfile
#    volumes:
#      - ./enigma-server/dist:/usr/share/nginx/html
    ports:
      - "3000:3000" #specify ports forewarding

  docs:
    build: docs # specify the directory of the Dockerfile
    ports:
      - "80:80" #specify ports forewarding
